const movies = [
  "Frisco Kid, The",
  "You're a Good Man, Charlie Brown",
  "Witness for the Prosecution",
  "Pajama Game, The",
  "For Ellen",
  "Maniac Cop 2",
  "Tell It to the Marines",
  "Aspen Extreme",
  "Man, The",
  "Mistaken for Strangers",
  "Malèna",
  "Jealousy",
  "Some Guy Who Kills People",
  "Race",
  "Expired",
  "Cleopatra",
  "Line, The (La linea)",
  "Ice Pirates, The",
  "Interrupted Melody",
  "Breaks, The",
  "Mating Habits of the Earthbound Human, The",
  "Miss March",
  "Dead Times (Temps morts, Les)",
  "While You Were Sleeping",
  "Lookin' to Get Out",
  "Hunt, The (Caza, La)",
  "Disappearance of Haruhi Suzumiya, The (Suzumiya Haruhi no shôshitsu)",
  "Secret Honor",
  "Evangelion: 2.0 You Can (Not) Advance (Evangerion shin gekijôban: Ha)",
  "In the Line of Fire",
  "Earth to Echo",
  "This Is the Army",
  "Black Beauty",
  "Hoodlum",
  "If Looks Could Kill",
  "Max Keeble's Big Move",
  "Saint Ralph",
  "Red Canyon",
  "Tarzan's New York Adventure",
  "300 Spartans, The",
  "Arcana",
  "Love Without Pity",
  "Bourne Identity, The",
  "Tenderness",
  "Annabel Takes a Tour (Annabel Takes a Trip)",
  "From B Movie to Cult Film: Western",
  "Last Wave, The",
  "Assassination Tango",
  "Funky Forest: The First Contact",
  "Eichmann",
  "Kismet",
  "The Hire: Beat the Devil",
  "Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The",
  "House of Tolerance",
  "Public Eye, The (Follow Me!)",
  "Swiss Family Robinson",
  "Amu",
  "Diary of a Wimpy Kid: Rodrick Rules",
  "Boogie Man: The Lee Atwater Story",
  "Two Can Play That Game",
  "Guardian Angel",
  "Heart of a Lion",
  "Very Potter Musical, A",
  "Freaky Deaky",
  "Till Human Voices Wake Us",
  "Boat That Rocked, The (a.k.a. Pirate Radio)",
  "Brick Mansions",
  "Sherlock Holmes: Terror by Night",
  "Pale Flower (Kawaita hana)",
  "My Mother's Smile (a.k.a. The Religion Hour) (L'ora di religione) (Il sorriso di mia madre)",
  "Octopus, The (Le poulpe)",
  "Accidental Golfer, The (Den ofrivillige golfaren)",
  "North Star (a.k.a. Tashunga)",
  "High School",
  "Pat Garrett and Billy the Kid",
  "Associate, The (Associé, L')",
  "Cougars, Inc.",
  "The Final Girl",
  "Stowaway",
  "Gossip",
  "Young Unknowns, The",
  "My Best Fiend (Mein liebster Feind)",
  "Prairie Fever",
  "Mr. Kinky",
  "Freaked",
  "Hurt",
  "Winning Streak",
  "Sophie's World (Sofies verden)",
  "Cosmonaut (Cosmonauta)",
  "7 Below (Seven Below)",
  "Crow: Salvation, The",
  "Dare",
  "April Captains (Capitães de Abril)",
  "Factory, The",
  "The Bronze",
  "Little Otik (Otesánek)",
  "Speed Racer",
  "Offside",
  "I Met Him in Paris",
  "Shunning, The",
];
